spring:
  datasource:
    url: jdbc:mysql://localhost:3306/development?charsetEncoding=UTF-8
    username: root
    password: root
  jpa:
    driverClassName: com.mysql.jdbc.Driver
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MySQL
    show-sql: true
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.ddl-auto: update
    hibernate:
      ddl-auto: update
server:
  port: 8080
